sudo: required

language: ruby

services:
- docker

before_install:
- docker pull najlabioinfo/najlabioinfospace

script:
- bundle exec rake test

- ./run 'docker run -it najlabioinfo/najlabioinfospace R'
