############################################################ 
# Dockerfile based on Centos Image 
############################################################ 
# Set the base image to use to Centos
FROM centos:7

# Set the file maintainer (your name - the file's author) 
MAINTAINER "Najla BEN HASSSINE" bhndevtools@gmail.com

#Prepare env and extra-package install
RUN yum install -y sudo epel-release-7-5.noarch.rpm deltarpm  addgroup

#MAKE PATH SHAR
RUN mkdir -p /usr/share/info
RUN useradd najlabioinfo \
    && chown najlabioinfo:najlabioinfo /home/najlabioinfo

#Install devtools
RUN yum -y groupinstall "Development Tools"  
RUN yum -y install curl git irb m4 ruby texinfo bzip2-devel curl-devel expat-devel ncurses-devel zlib-devel

RUN yum install -y ghostscript wget cmake git github-backup pandoc gcc g++ kernel-devel  deltarpm htop kpathsea which latex web2c dvips libRmath-devel libRmath zip libreadline-dev readline-devel libreadline pdftailor pdftk mozilla tiff2pdf qpdf xpdf evince which
RUN yum install -y gcc-c++ cairo-devel libpng-devel libX11 libX11-devel qt libjpeg-turbo java  info xorg-x11-server-Xvfb firefox texlive

#Needed package for R
RUN yum -y groupinstall X11
RUN yum install -y  libXt-dev libgtk2.0-dev libcairo2-dev xvfb xauth xfonts-base zip libreadline-dev readline-devel libreadline pdftailor pdftk mozilla tiff2pdf texlive qpdf xpdf evince which pdftohtml texinfo inconsolata-fonts

#Updating package
RUN yum update -y

#Updating package
RUN yum install -y  curl gcc make perl git perl-devel expat-devel zlib-devel libbamtools links pdftohtml

#METHODE A
#-INSTALL firepony
RUN curl -o /etc/yum.repos.d/packages.shadau.com.repo \
    http://packages.shadau.com/rpm/centos-7/packages.shadau.com.repo
RUN yum install -y firepony

#check firepony install
#RUN firepony -v

#INSTALL R BEDTools

#___________BIOINFO/SOFTW_C_FEB16
#INSTALL BWA 
RUN git clone https://github.com/lh3/bwa.git \
    && cd bwa; make \
    && cp bwa /usr/bin/ \
    && cd .. && rm -r -f bwa

#INSTALL BOWTIE2
RUN wget https://github.com/BenLangmead/bowtie2/archive/v2.2.5.tar.gz \
    && tar xfz v2.2.5.tar.gz \
    && cd bowtie2-2.2.5/; make \
    && cp bowtie2* /usr/bin/ \
    && cd .. && rm -r -f bowtie2-2.2.5/ v2.2.5.tar.gz

# INSTALL bamtools 
RUN git clone git://github.com/pezmaster31/bamtools.git && cd bamtools \
    && mkdir build && cd build \
    && cmake .. \
    && make \
    && cd .. \
    && cp bin/bamtools* /usr/local/bin/ \
    && cd .. \
    && rm -r bamtools/
    
# INSTALL samtools 
RUN wget http://sourceforge.net/projects/samtools/files/latest/download/samtools-1.3.tar.bz2 \
    && tar -xvf samtools-1.3.tar.bz2 \
    && cd samtools-1.3/; make install
    
# INSTALL R
RUN yum install -y epel-release
RUN yum repolist disabled
RUN yum install -y R BEDTools

## INSTALL SHINY
RUN Rscript -e 'install.packages(c("devtools", "dplyr", "ggplot2", "reshape2","testthat","shiny","shinythemes","shinydashboard"),repos = "http://cran.us.r-project.org")' \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds
## INSTALL BIOCODUCTOR
#RUN Rscript -e 'source("http://bioconductor.org/biocLite.R"); \
#                biocLite(c("DiffBind", "DESeq", "GenomicRanges", "ballgown"))' \
#    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

# Default action 
CMD ["/bin/bash"]
